from typing import NewType, Union, Literal


Language = NewType(
    "Language",
    Union[
        Literal["af"],  # "Afrikaans",
        Literal["am"],  # "Amharic",
        Literal["ar"],  # "Arabic",
        Literal["bg"],  # "Bulgarian",
        Literal["bn"],  # "Bengali",
        Literal["bs"],  # "Bosnian",
        Literal["ca"],  # "Catalan",
        Literal["cs"],  # "Czech",
        Literal["cy"],  # "Welsh",
        Literal["da"],  # "Danish",
        Literal["de"],  # "German",
        Literal["el"],  # "Greek",
        Literal["en"],  # "English",
        Literal["es"],  # "Spanish",
        Literal["et"],  # "Estonian",
        Literal["eu"],  # "Basque",
        Literal["fi"],  # "Finnish",
        Literal["fr"],  # "French",
        Literal["gl"],  # "Galician",
        Literal["gu"],  # "Gujarati",
        Literal["ha"],  # "Hausa",
        Literal["hi"],  # "Hindi",
        Literal["hr"],  # "Croatian",
        Literal["hu"],  # "Hungarian",
        Literal["id"],  # "Indonesian",
        Literal["is"],  # "Icelandic",
        Literal["it"],  # "Italian",
        Literal["iw"],  # "Hebrew",
        Literal["ja"],  # "Japanese",
        Literal["jw"],  # "Javanese",
        Literal["km"],  # "Khmer",
        Literal["kn"],  # "Kannada",
        Literal["ko"],  # "Korean",
        Literal["la"],  # "Latin",
        Literal["lt"],  # "Lithuanian",
        Literal["lv"],  # "Latvian",
        Literal["ml"],  # "Malayalam",
        Literal["mr"],  # "Marathi",
        Literal["ms"],  # "Malay",
        Literal["my"],  # "Myanmar (Burmese)",
        Literal["ne"],  # "Nepali",
        Literal["nl"],  # "Dutch",
        Literal["no"],  # "Norwegian",
        Literal["pa"],  # "Punjabi (Gurmukhi)",
        Literal["pl"],  # "Polish",
        Literal["pt"],  # "Portuguese (Brazil)",
        Literal["pt-]P,T"],  # ": "Portuguese (Portugal)"
        Literal["ro"],  # "Romanian",
        Literal["ru"],  # "Russian",
        Literal["si"],  # "Sinhala",
        Literal["sk"],  # "Slovak",
        Literal["sq"],  # "Albanian",
        Literal["sr"],  # "Serbian",
        Literal["su"],  # "Sundanese",
        Literal["sv"],  # "Swedish",
        Literal["sw"],  # "Swahili",
        Literal["ta"],  # "Tamil",
        Literal["te"],  # "Telugu",
        Literal["th"],  # "Thai",
        Literal["tl"],  # "Filipino",
        Literal["tr"],  # "Turkish",
        Literal["uk"],  # "Ukrainian",
        Literal["ur"],  # "Urdu",
        Literal["vi"],  # "Vietnamese",
        Literal["yue"],  # "Cantonese",
        Literal["zh-CN,"],  # ": "Chinese (Simplified)"
        Literal["zh-TW"],  # ": "Chinese (Traditional)"
    ],
)
